-- MySQL Script generated by MySQL Workbench
-- ter 15 set 2020 23:04:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema artesup
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `artesup` ;

-- -----------------------------------------------------
-- Schema artesup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artesup` DEFAULT CHARACTER SET utf8 ;
USE `artesup` ;

-- -----------------------------------------------------
-- Table `artesup`.`queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artesup`.`queue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(10) NOT NULL DEFAULT 'queued',
  `transaction_id` VARCHAR(45) NOT NULL,
  `feedback_url` VARCHAR(256) NOT NULL,
  `watermark_path` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `artesup`.`queue_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artesup`.`queue_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `queue_id` INT NOT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'queued',
  `position_x` INT(5) NULL,
  `position_y` INT(5) NULL,
  `position_height` INT(5) NULL,
  `position_width` INT(5) NULL,
  `base_image_path` VARCHAR(256) NOT NULL,
  `s3_image_path` VARCHAR(256) NOT NULL,
  `details` TEXT NULL,
  PRIMARY KEY (`id`, `queue_id`),
  INDEX `fk_queue_items_queue_idx` (`queue_id` ASC),
  CONSTRAINT `fk_queue_items_queue`
    FOREIGN KEY (`queue_id`)
    REFERENCES `artesup`.`queue` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
