version: '3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - ./.data:/var/lib/mysql
      - ./database-schemes:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: webapp
  api:
    image: node:10-alpine
    ports:
      - "3000:3000"
    container_name: node-container
    user: node
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: npm start
    depends_on:
      - db
