version: "3.8"
services:
  watermark:
    build: .
    container_name: watermark
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - "3000:3000"
    entrypoint: "npm start"
    env_file: .env
    environment:
      "EXPRESS_PORT": "3000"
      "NODE_ENV": "development"
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: watermark-mysql
    volumes:
      - ./.data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      "MYSQL_DATABASE": "${DB_DATABASE}"
      "MYSQL_ROOT_PASSWORD": "${DB_PASSWORD}"
    networks:
      - backend

networks:
  backend:
    name: artesup_network
